spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4e76269fc93f47cfaba96f380ddbcf67
            redirect-uri: http://localhost:8080/auth/kakao/callback
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    jwt:
      secret-key: q_W?DNW;gK"[S8k}q{J>!8lDvH<SL#p8E;f&SA7:^p9rJPQ"`CaSM_vfyynbq8I
      access-token:
        expiration: 216000
      refresh-token:
        expiration: 518400

logging:
  level:
    org:
      springframework:
        security: DEBUG

KAKAO_LOGOUT_URL: https://kauth.kakao.com/oauth/logout
KAKAO_LOGOUT_REDIRECT_URI: http://localhost:8080/auth/kakao/logout/callback
CLIENT_BASE_URL: http://localhost:3000